In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3])
b = np.array([2])
print(a*b)

[2 4 6]


In [14]:
#Numpy Shapes
a = np.zeros(4)
print(f"a: {a}, a.shape = {a.shape}")

a: [0. 0. 0. 0.], a.shape = (4,)


In [24]:
b1 = np.array([1,2,3,4])
print(f"b1:{b1}, b1.shape:{b1.shape}")
b2 = np.array([[1,2,3,4],[5,6,7,8]])
print(f"b2: {b2}, b2.shape = {b2.shape}")

b1:[1 2 3 4], b1.shape:(4,)
b2: [[1 2 3 4]
 [5 6 7 8]], b2.shape = (2, 4)


In [42]:
c1 = np.arange(5)
print(c)
c2 = np.random.rand(5)
print(c2)

[0 1 2 3 4]
[0.13720665 0.62850816 0.61948319 0.75766823 0.87829281]


<h3>Reshape is used to change the dimension of an array. '-1' often says to calculate the number of rows given the number of columns and value/number of elements

In [44]:
a = np.arange(6).reshape(-1,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [47]:
b = np.arange(6).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [50]:
c = np.arange(6).reshape(-1,3)
print(c)

[[0 1 2]
 [3 4 5]]
